#!/bin/bash


sed -i 's|bootsplash-biglinux||g' /etc/mkinitcpio.conf 2> /dev/null

sed -i 's|bootsplash.bootfile=/bootsplash-themes/biglinux/bootsplash||g' /etc/default/grub 2> /dev/null


mkinitcpio -P
update-grub
