#!/bin/bash

# Add bootsplash-biglinux in mkinitcpio
if [ "$(grep bootsplash-biglinux /etc/mkinitcpio.conf)" = "" ]; then
    sed -i 's|HOOKS="|HOOKS="bootsplash-biglinux |g' /etc/mkinitcpio.conf
fi

# Add bootsplash-biglinux in grub
if [ "$(grep 'bootsplash.bootfile=/bootsplash-themes/biglinux/bootsplash' /etc/default/grub)" = "" ]; then
    sed -i 's|GRUB_CMDLINE_LINUX_DEFAULT="|GRUB_CMDLINE_LINUX_DEFAULT="bootsplash.bootfile=/bootsplash-themes/biglinux/bootsplash |g' /etc/default/grub
fi

mkinitcpio -P
update-grub
